spring.application.name=feign-client
spring.main.allow-bean-definition-overriding=true
server.servlet.context-path=/
logging.level.root=INFO
logging.level.com.globant.feign.client=DEBUG
server.port=8080
spring.profiles.active=local
user.service.url=http://localhost:8085/api/v1